"""
Django settings for discordblindtest project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

import dj_database_url
from django.contrib import messages
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = os.environ.get('DEBUG', 'False').lower() in ('1', 'true', 'yes', 'on')

SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-development-only'
    else:
        raise ImproperlyConfigured('The SECRET_KEY environment variable is required.')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split()


# Discord

DISCORD_TOKEN = os.environ.get('DISCORD_TOKEN')
# Guilds to sync slash commands to immediately; comma-separated.
TEST_GUILD_IDS = [guild_id.strip() for guild_id
                  in os.environ.get('TEST_GUILD_ID', '').split(' ')
                  if guild_id.strip()]

# Discord OAuth2 of the same application, used by the web admin login.
DISCORD_CLIENT_ID = os.environ.get('DISCORD_CLIENT_ID')
DISCORD_CLIENT_SECRET = os.environ.get('DISCORD_CLIENT_SECRET')
DISCORD_REDIRECT_URI = os.environ.get('DISCORD_REDIRECT_URI')


# Application definition

INSTALLED_APPS = [
    'discordcore',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blindtest',
    'discordbot',
    'webadmin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'discordblindtest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'discordblindtest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(conn_max_age=600,
                                      conn_health_checks=True),
}


# Cache
# https://docs.djangoproject.com/en/6.1/ref/settings/#caches

REDIS_URL = os.environ.get('REDIS_URL')

# The tests clear the cache by flushing a whole Redis database, so they run on
# another one, the way they run on a database of their own.
TEST_COMMANDS = ('test', 'testserver')
CACHE_TEST_INDEX = int(os.environ.get('CACHE_TEST_INDEX', 15))


def running_tests() -> bool:
    """Return True when the command being run is the test suite."""
    return len(sys.argv) > 1 and sys.argv[1] in TEST_COMMANDS


def cache_location(redis_url: str | None) -> str:
    """Return the cache location, on the test database when running tests."""
    if not redis_url:
        return 'blindtest'
    if not running_tests():
        return redis_url
    return urlunsplit(urlsplit(redis_url)._replace(path=f'/{CACHE_TEST_INDEX}'))


CACHES = {
    'default': {
        'BACKEND': ('django.core.cache.backends.redis.RedisCache' if REDIS_URL
                    else 'django.core.cache.backends.locmem.LocMemCache'),
        'LOCATION': cache_location(REDIS_URL),
        'KEY_PREFIX': 'blindtest',
        # Entries carry their own lifetime; this one only catches the rest.
        'TIMEOUT': 3600,
        # A cache that stops answering must not hold the bot's commands.
        'OPTIONS': {'socket_timeout': 2, 'socket_connect_timeout': 2},
    },
}


# Authentication

AUTH_USER_MODEL = 'discordcore.Player'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'webadmin:login'
LOGIN_REDIRECT_URL = 'webadmin:dashboard'
LOGOUT_REDIRECT_URL = 'webadmin:login'

# Bootstrap names an error alert "danger"; Django tags it "error".
MESSAGE_TAGS = {messages.ERROR: 'danger'}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}


# Logging
# https://docs.djangoproject.com/en/6.1/topics/logging/

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '{asctime} {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'discord': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
