# Generated by Django 6.1.1 on 2026-09-28 19:44

import discordcore.mentions
import discordcore.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField(unique=True, verbose_name='Discord guild ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'guild',
                'verbose_name_plural': 'guilds',
                'ordering': ('name', 'discord_id'),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('discord_user_id', models.BigIntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Discord user ID')),
                ('discord_name', models.CharField(blank=True, default=None, max_length=200, null=True, unique=True, verbose_name='Discord username')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
            managers=[
                ('objects', discordcore.models.PlayerManager()),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention', models.CharField(help_text='A user mention (<@123456789>) or a role mention (<@&123456789>).', max_length=100, validators=[discordcore.mentions.validate_mention], verbose_name='Discord mention')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='discordcore.guild', verbose_name='guild')),
            ],
            options={
                'verbose_name': 'host',
                'verbose_name_plural': 'hosts',
                'ordering': ('guild', 'mention'),
                'constraints': [models.UniqueConstraint(models.F('guild'), models.F('mention'), name='unique_host_per_guild', violation_error_message='This user or role is already a host of this server.')],
            },
        ),
    ]
