# Generated by Django 6.1.1 on 2026-10-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='default_channel_id',
            field=models.BigIntegerField(blank=True, help_text='Where games of this server are played when the host names no channel.', null=True, verbose_name='default channel ID'),
        ),
    ]
