# Generated by Django 6.1.1 on 2026-10-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordcore', '0002_guild_default_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='default_ping_role_id',
            field=models.BigIntegerField(blank=True, help_text='The default role pinged when a game of this server is published and each round opens.', null=True, verbose_name='default ping role ID'),
        ),
    ]
