# Generated by Django 6.1.1 on 2026-09-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'ordering': ('text',),
            },
        ),
        migrations.CreateModel(
            name='AnswerVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='variant text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'answer variant',
                'verbose_name_plural': 'answer variants',
                'ordering': ('answer', 'text'),
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(verbose_name='Discord channel ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('type', models.CharField(choices=[('BLIND_TEST', 'blind test'), ('OPEN', 'open question'), ('MULTIPLE_CHOICE', 'multiple choice')], default='BLIND_TEST', max_length=20, verbose_name='type')),
                ('state', models.CharField(choices=[('SETUP', 'being prepared'), ('RUNNING', 'running'), ('PAUSED', 'paused'), ('FINISHED', 'finished')], default='RUNNING', max_length=20, verbose_name='state')),
                ('scoring_mode', models.CharField(choices=[('STANDARD', 'standard (fixed points)'), ('FIRST_ONLY', 'first correct only'), ('SPEED', 'speed / time bonus')], default='STANDARD', max_length=20, verbose_name='scoring mode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, verbose_name='guessed text')),
                ('secondary_text', models.CharField(blank=True, max_length=200, verbose_name='secondary text')),
                ('text_correct', models.BooleanField(default=False, verbose_name='text correct')),
                ('secondary_correct', models.BooleanField(default=False, verbose_name='secondary correct')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
            ],
            options={
                'verbose_name': 'guess',
                'verbose_name_plural': 'guesses',
                'ordering': ('round', 'submitted_at'),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(blank=True, max_length=500, verbose_name='prompt')),
                ('media_url', models.URLField(blank=True, verbose_name='media URL')),
                ('album', models.CharField(blank=True, max_length=200, verbose_name='album')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='number')),
                ('type', models.CharField(blank=True, choices=[('BLIND_TEST', 'blind test'), ('OPEN', 'open question'), ('MULTIPLE_CHOICE', 'multiple choice')], default='', help_text='Inherits from the game type if left empty.', max_length=20, verbose_name='type')),
                ('scoring_mode', models.CharField(blank=True, choices=[('STANDARD', 'standard (fixed points)'), ('FIRST_ONLY', 'first correct only'), ('SPEED', 'speed / time bonus')], default='', help_text='Inherits from the game scoring mode if left empty.', max_length=20, verbose_name='scoring mode')),
                ('started_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='started at')),
                ('revealed_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='revealed at')),
            ],
            options={
                'verbose_name': 'round',
                'verbose_name_plural': 'rounds',
                'ordering': ('game', 'index'),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'ordering': ('game', 'name'),
            },
        ),
    ]
