# Generated by Django 6.1.1 on 2026-09-28 19:44

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blindtest', '0001_initial'),
        ('discordcore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='guild',
            field=models.ForeignKey(blank=True, help_text='Leave empty for the global library.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='discordcore.guild', verbose_name='guild'),
        ),
        migrations.AddField(
            model_name='answervariant',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='blindtest.answer', verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='game',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='discordcore.guild', verbose_name='guild'),
        ),
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_games', to=settings.AUTH_USER_MODEL, verbose_name='host'),
        ),
        migrations.AddField(
            model_name='guess',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guesses', to=settings.AUTH_USER_MODEL, verbose_name='player'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, help_text='Options for multiple choice questions.', related_name='choice_for_questions', to='blindtest.answer', verbose_name='choices'),
        ),
        migrations.AddField(
            model_name='question',
            name='expected_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expected_for_questions', to='blindtest.answer', verbose_name='expected answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='guild',
            field=models.ForeignKey(blank=True, help_text='Leave empty for the global library.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='discordcore.guild', verbose_name='guild'),
        ),
        migrations.AddField(
            model_name='question',
            name='secondary_answer',
            field=models.ForeignKey(blank=True, help_text='Artist for blind tests, or secondary required answer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_for_questions', to='blindtest.answer', verbose_name='secondary answer'),
        ),
        migrations.AddField(
            model_name='round',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='blindtest.game', verbose_name='game'),
        ),
        migrations.AddField(
            model_name='round',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='blindtest.question', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='guess',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='blindtest.round', verbose_name='round'),
        ),
        migrations.AddField(
            model_name='team',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='blindtest.game', verbose_name='game'),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='players'),
        ),
        migrations.AddField(
            model_name='guess',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='blindtest.team', verbose_name='team'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('text'), models.F('guild'), name='unique_answer_text', nulls_distinct=False, violation_error_message='This answer already exists.'),
        ),
        migrations.AddConstraint(
            model_name='answervariant',
            constraint=models.UniqueConstraint(models.F('answer'), django.db.models.functions.text.Lower('text'), name='unique_answer_variant', violation_error_message='This variant is already registered for this answer.'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(models.F('guild'), condition=models.Q(('state', 'FINISHED'), _negated=True), name='unique_active_game_per_guild', violation_error_message='A game is already running in this server.'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(models.F('game'), models.F('index'), name='unique_round_number', violation_error_message='This round number is already used in this game.'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(models.F('game'), models.F('name'), name='unique_team_name_per_game', violation_error_message='This team name is already used in this game.'),
        ),
        migrations.AddConstraint(
            model_name='guess',
            constraint=models.UniqueConstraint(models.F('round'), models.F('player'), name='unique_guess_per_round', violation_error_message='This player already answered this round.'),
        ),
    ]
