# Generated by Django 6.1.1 on 2026-10-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindtest', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ping_role_id',
            field=models.BigIntegerField(blank=True, help_text='The role pinged for the game when it is published and each round opens.', null=True, verbose_name='ping role ID'),
        ),
    ]
