# Generated by Django 6.1.1 on 2026-10-04 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindtest', '0003_game_ping_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ANNOUNCE', 'announcement'), ('ROUND', 'round opened'), ('REVEAL', 'round answer and scores'), ('RECAP', 'final scores')], max_length=20, verbose_name='kind')),
                ('status', models.CharField(choices=[('PENDING', 'waiting to be posted'), ('CLAIMED', 'being posted'), ('SENT', 'posted'), ('FAILED', 'could not be posted')], default='PENDING', max_length=10, verbose_name='status')),
                ('claimed_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='claimed at')),
                ('sent_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='sent at')),
                ('message_ids', models.JSONField(blank=True, default=list, verbose_name='message ids')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='blindtest.game', verbose_name='game')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='blindtest.round', verbose_name='round')),
            ],
            options={
                'verbose_name': 'broadcast',
                'verbose_name_plural': 'broadcasts',
                'ordering': ('created_at', 'pk'),
                'indexes': [models.Index(fields=['status', 'created_at'], name='blindtest_b_status_d25050_idx')],
            },
        ),
    ]
