# Generated by Django 6.1.1 on 2026-10-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindtest', '0004_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='attempts'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='next attempt at'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='status',
            field=models.CharField(choices=[('PENDING', 'waiting to be posted'), ('CLAIMED', 'being posted'), ('SENT', 'posted'), ('FAILED', 'waiting to be tried again'), ('DEAD', 'given up on')], default='PENDING', max_length=10, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['status', 'next_attempt_at'], name='blindtest_b_status_9602cf_idx'),
        ),
    ]
