# Generated by Django 6.1.1 on 2026-10-05 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindtest', '0006_published_games'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='guess',
            name='unique_guess_per_round',
            constraint=models.UniqueConstraint(models.F('round'), models.F('player'), name='unique_guess_per_round', violation_error_message='This player already guessed this round.'),
        ),
    ]
